<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompanyEmployees.Domain\CompanyEmployees.Domain.csproj" />
    <ProjectReference Include="..\CompanyEmployees.Gateway\CompanyEmployees.Gateway.csproj" />
  </ItemGroup>

</Project>
